"""
Pusher Agent - Main controller for all other agents
Orchestrates the flow between commands and specialized agents
"""
import logging
import discord
from datetime import datetime, timedelta
import os

from config import AGENT_NAMES, COLORS
from agents.identity_agent import IdentityAgent
from agents.card_agent import CardAgent
from agents.email_agent import EmailAgent
from agents.phone_agent import PhoneAgent
from agents.automation_agent import AutomationAgent
from agents.payment_agent import PaymentAgent

logger = logging.getLogger(__name__)

class Pusher:
    """Main controller for all specialized agents"""
    
    def __init__(self, db):
        """Initialize the pusher with all agents"""
        self.db = db
        
        # Check if RapidAPI key is available
        rapidapi_key = os.getenv("RAPIDAPI_KEY")
        if not rapidapi_key:
            logger.warning("RAPIDAPI_KEY not found in environment variables. API requests will likely fail.")
        
        # Initialize all specialized agents
        self.identity_agent = IdentityAgent(db)
        self.card_agent = CardAgent(db)
        self.email_agent = EmailAgent(db)
        self.phone_agent = PhoneAgent(db)
        self.automation_agent = AutomationAgent(db)
        self.payment_agent = PaymentAgent(db)
        
        # Check if Solana wallet is available
        solana_wallet = os.getenv("SOLANA_WALLET_ADDRESS")
        if not solana_wallet or solana_wallet == "YourSolanaWalletAddressHere":
            logger.warning("SOLANA_WALLET_ADDRESS not properly configured. Payment features will use a placeholder address.")
        
        logger.info("Pusher agent initialized with all specialized agents")
    
    async def process_hit(self, user_id, username, service):
        """Process a full trial setup with all agents"""
        logger.info(f"Processing hit command for {username} ({user_id}) - Service: {service}")
        
        # Ensure user exists in database
        self.db.create_user(user_id, username)
        
        # Generate identity data
        identity = await self.identity_agent.generate_identity()
        self.db.save_credential(user_id, service, "identity", identity)
        
        # Generate email
        email = await self.email_agent.generate_email(identity)
        self.db.save_credential(user_id, service, "email", email)
        
        # Generate card
        card = await self.card_agent.generate_card()
        self.db.save_credential(user_id, service, "card", card)
        
        # Generate phone
        phone = await self.phone_agent.generate_phone()
        self.db.save_credential(user_id, service, "phone", phone)
        
        # Log the command
        self.db.log_command(user_id, "hit", service)
        
        # Create response embed
        embed = discord.Embed(
            title=f"🎯 Trial Ready for {service}",
            description=f"All credentials generated by **The Pusher** for your {service} trial.",
            color=COLORS["success"],
            timestamp=datetime.now()
        )
        
        embed.add_field(name="👤 Identity", value=f"Name: **{identity['name']}**\nAge: **{identity['age']}**\nLocation: **{identity['location']}**", inline=False)
        embed.add_field(name="📧 Email", value=f"**{email}**", inline=True)
        embed.add_field(name="📱 Phone", value=f"**{phone}**", inline=True)
        embed.add_field(name="💳 Card", value=f"**{card['number']}**\nExp: **{card['expiry']}**\nCVV: **{card['cvv']}**", inline=False)
        embed.add_field(name="Usage", value="Use `!stash` to view your saved credentials", inline=False)
        
        embed.set_footer(text=f"Requested by {username} | Trial Junkie", icon_url="https://cdn.discordapp.com/embed/avatars/0.png")
        
        return embed
    
    async def process_dose(self, user_id, username, agent_type, platform):
        """Process a partial credential generation with a single agent"""
        logger.info(f"Processing dose command for {username} ({user_id}) - Agent: {agent_type}, Platform: {platform}")
        
        # Ensure user exists in database
        self.db.create_user(user_id, username)
        
        # Map agent type to the corresponding agent
        agent_type = agent_type.lower()
        
        # Determine agent and operation
        if agent_type == "harry":
            # Identity generation
            result = await self.identity_agent.generate_identity()
            cred_type = "identity"
            display_value = f"Name: **{result['name']}**\nAge: **{result['age']}**\nLocation: **{result['location']}**"
            agent_name = AGENT_NAMES["harry"]
            
        elif agent_type == "mandy":
            # Card generation
            result = await self.card_agent.generate_card()
            cred_type = "card"
            display_value = f"Number: **{result['number']}**\nExp: **{result['expiry']}**\nCVV: **{result['cvv']}**"
            agent_name = AGENT_NAMES["mandy"]
            
        elif agent_type == "xan":
            # Email generation
            identity = await self.identity_agent.generate_identity()
            result = await self.email_agent.generate_email(identity)
            cred_type = "email"
            display_value = f"**{result}**"
            agent_name = AGENT_NAMES["xan"]
            
        elif agent_type == "phone":
            # Phone generation
            result = await self.phone_agent.generate_phone()
            cred_type = "phone"
            display_value = f"**{result}**"
            agent_name = AGENT_NAMES["phone"]
            
        else:
            raise ValueError(f"Unknown agent type: {agent_type}")
        
        # Save the credential
        self.db.save_credential(user_id, platform, cred_type, result)
        
        # Log the command
        self.db.log_command(user_id, "dose", f"{agent_type} {platform}")
        
        # Create response embed
        embed = discord.Embed(
            title=f"💊 Dose Ready for {platform}",
            description=f"Credential generated by **{agent_name}** for your {platform} account.",
            color=COLORS["info"],
            timestamp=datetime.now()
        )
        
        embed.add_field(name=f"{cred_type.title()}", value=display_value, inline=False)
        embed.add_field(name="Usage", value="Use `!stash` to view your saved credentials", inline=False)
        
        embed.set_footer(text=f"Requested by {username} | Trial Junkie", icon_url="https://cdn.discordapp.com/embed/avatars/0.png")
        
        return embed
    
    async def process_trip(self, user_id, username, script):
        """Process an automation script run"""
        logger.info(f"Processing trip command for {username} ({user_id}) - Script: {script}")
        
        # Ensure user exists in database
        self.db.create_user(user_id, username)
        
        # Get user's latest credentials
        credentials = self.db.get_user_credentials(user_id)
        
        if not credentials:
            raise ValueError("No credentials found. Generate some first with !hit or !dose")
        
        # Run the automation script
        result = await self.automation_agent.run_script(script, credentials)
        
        # Log the command
        self.db.log_command(user_id, "trip", script)
        
        # Create response embed
        embed = discord.Embed(
            title=f"🍄 Trip Report: {script}",
            description=f"Automation run by **{AGENT_NAMES['sal']}** for script `{script}`.",
            color=COLORS["warning"],
            timestamp=datetime.now()
        )
        
        embed.add_field(name="Status", value=result["status"], inline=False)
        embed.add_field(name="Details", value=result["details"], inline=False)
        
        if "steps" in result:
            embed.add_field(name="Steps Completed", value="\n".join(f"✅ {step}" for step in result["steps"]), inline=False)
        
        embed.set_footer(text=f"Requested by {username} | Trial Junkie", icon_url="https://cdn.discordapp.com/embed/avatars/0.png")
        
        return embed
    
    async def process_stash(self, user_id, username):
        """Process a stash view request"""
        logger.info(f"Processing stash command for {username} ({user_id})")
        
        # Ensure user exists in database
        self.db.create_user(user_id, username)
        
        # Get user stats
        stats = self.db.get_user_stats(user_id)
        
        # Get user's credentials
        credentials = self.db.get_user_credentials(user_id)
        
        # Log the command
        self.db.log_command(user_id, "stash", "")
        
        # Create response embed
        embed = discord.Embed(
            title=f"🧪 Your Trial Junkie Stash",
            description=f"All your saved credentials and trial data.",
            color=COLORS["info"],
            timestamp=datetime.now()
        )
        
        # Add stats
        total_creds = stats.get('total_credentials', 0)
        embed.add_field(name="📊 Stats", value=f"Total Items: **{total_creds}**\nServices: **{len(set(c['service'] for c in credentials))}**", inline=False)
        
        # Group credentials by service
        services = {}
        for cred in credentials:
            if cred['service'] not in services:
                services[cred['service']] = []
            services[cred['service']].append(cred)
        
        # Add latest credentials for each service (up to 3 services)
        for i, (service, creds) in enumerate(list(services.items())[:3]):
            # Group by credential type
            service_data = {}
            for cred in creds:
                if cred['type'] not in service_data:
                    service_data[cred['type']] = cred['value']
            
            # Format the credential data
            cred_text = []
            if 'identity' in service_data:
                identity = service_data['identity']
                cred_text.append(f"👤 **{identity['name']}** ({identity['age']})")
            
            if 'email' in service_data:
                cred_text.append(f"📧 **{service_data['email']}**")
            
            if 'phone' in service_data:
                cred_text.append(f"📱 **{service_data['phone']}**")
            
            if 'card' in service_data:
                card = service_data['card']
                cred_text.append(f"💳 **{card['number']}** (Exp: {card['expiry']})")
            
            # Add field for this service
            embed.add_field(
                name=f"🔑 {service}",
                value="\n".join(cred_text) or "No details available",
                inline=False
            )
        
        # If there are more services, indicate that
        if len(services) > 3:
            remaining = len(services) - 3
            embed.add_field(
                name="➕ More Services",
                value=f"**{remaining}** more services not shown. Use `!hit <service>` to generate more.",
                inline=False
            )
        
        embed.set_footer(text=f"Requested by {username} | Trial Junkie", icon_url="https://cdn.discordapp.com/embed/avatars/0.png")
        
        return embed
    
    async def process_rehab(self, user_id, username):
        """Process a rehab (data clearing) request"""
        logger.info(f"Processing rehab command for {username} ({user_id})")
        
        # Ensure user exists in database
        self.db.create_user(user_id, username)
        
        # Clear user data
        self.db.clear_user_data(user_id)
        
        # Log the command
        self.db.log_command(user_id, "rehab", "")
        
        # Create response embed
        embed = discord.Embed(
            title=f"🏥 Rehab Complete",
            description=f"Your credentials have been cleared. You're clean now.",
            color=COLORS["success"],
            timestamp=datetime.now()
        )
        
        embed.add_field(name="Status", value="✅ **All credentials deleted**", inline=False)
        embed.add_field(name="What's Next", value="Use `!hit <service>` to start generating new trials", inline=False)
        
        embed.set_footer(text=f"Requested by {username} | Trial Junkie", icon_url="https://cdn.discordapp.com/embed/avatars/0.png")
        
        return embed
        
    async def process_payment(self, user_id, username, service_type):
        """Process a payment request"""
        logger.info(f"Processing payment request for {username} ({user_id}) - Service: {service_type}")
        
        # Ensure user exists in database
        self.db.create_user(user_id, username)
        
        # Create a payment request
        payment_info = await self.payment_agent.create_payment(user_id, username, service_type)
        
        # Log the command
        self.db.log_command(user_id, "pay", service_type)
        
        # Create response embed
        embed = discord.Embed(
            title=f"💰 Payment Required for {service_type}",
            description=f"Payment request generated by **{AGENT_NAMES['craig']}** for {service_type}.",
            color=COLORS["payment"],
            timestamp=datetime.now()
        )
        
        embed.add_field(
            name="Amount", 
            value=f"**{payment_info['amount']} SOL**", 
            inline=True
        )
        
        embed.add_field(
            name="Wallet Address", 
            value=f"```{payment_info['wallet']}```", 
            inline=False
        )
        
        embed.add_field(
            name="Reference", 
            value=f"```{payment_info['reference']}```", 
            inline=False
        )
        
        embed.add_field(
            name="Instructions", 
            value=(
                "1. Send the exact amount to the wallet address above\n"
                "2. Include the reference in the transaction memo\n"
                "3. Use `!verify_payment` to check the status"
            ), 
            inline=False
        )
        
        embed.add_field(
            name="Expires", 
            value=f"<t:{int(datetime.fromisoformat(payment_info['expires']).timestamp())}:R>", 
            inline=True
        )
        
        embed.set_footer(text=f"Requested by {username} | Trial Junkie", icon_url="https://cdn.discordapp.com/embed/avatars/0.png")
        
        return embed
    
    async def process_verify_payment(self, user_id, username, reference=None):
        """Verify a payment"""
        logger.info(f"Verifying payment for {username} ({user_id})")
        
        # Ensure user exists in database
        self.db.create_user(user_id, username)
        
        # Check payment status
        is_paid = await self.payment_agent.check_payment(user_id, reference)
        
        # Log the command
        self.db.log_command(user_id, "verify_payment", reference or "")
        
        # Get payment status
        status = await self.payment_agent.get_payment_status(user_id)
        
        # Create response embed based on payment status
        if status['status'] == 'completed' or is_paid:
            # Payment was successful
            
            # Update user tier based on the service type
            payment = self.db.get_payment_by_reference(reference or status.get('reference', ''))
            if payment and payment['service_type'] == 'premium':
                # Set premium membership for 30 days
                expiry_date = (datetime.now() + timedelta(days=30)).isoformat()
                self.db.update_user_tier(user_id, 'premium', expiry_date)
            
            embed = discord.Embed(
                title="✅ Payment Verified",
                description="Your payment has been successfully verified!",
                color=COLORS["success"],
                timestamp=datetime.now()
            )
            
            embed.add_field(
                name="Status", 
                value="**Payment Complete**", 
                inline=False
            )
            
            embed.add_field(
                name="Next Steps", 
                value="You can now use the premium features of Trial Junkie!", 
                inline=False
            )
            
        elif status['status'] == 'expired':
            # Payment request expired
            embed = discord.Embed(
                title="⏱️ Payment Expired",
                description="Your payment request has expired.",
                color=COLORS["error"],
                timestamp=datetime.now()
            )
            
            embed.add_field(
                name="What Now?", 
                value="You can create a new payment request using the `!pay` command.", 
                inline=False
            )
            
        else:
            # Payment still pending
            embed = discord.Embed(
                title="⏳ Payment Pending",
                description="Your payment has not been verified yet.",
                color=COLORS["warning"],
                timestamp=datetime.now()
            )
            
            embed.add_field(
                name="Status", 
                value=f"**{status['message']}**", 
                inline=False
            )
            
            if 'time_left' in status:
                embed.add_field(
                    name="Time Remaining", 
                    value=f"**{status['time_left'] // 60}m {status['time_left'] % 60}s**", 
                    inline=True
                )
            
            embed.add_field(
                name="Reference", 
                value=f"```{status.get('reference', 'N/A')}```" if 'reference' in status else "No reference found", 
                inline=False
            )
            
            embed.add_field(
                name="Instructions", 
                value=(
                    "1. Make sure you've sent the payment to the correct wallet address\n"
                    "2. Ensure you included the reference in the transaction memo\n"
                    "3. Wait for blockchain confirmation (may take a few minutes)\n"
                    "4. Use `!verify_payment` again to check status"
                ), 
                inline=False
            )
        
        embed.set_footer(text=f"Requested by {username} | Trial Junkie", icon_url="https://cdn.discordapp.com/embed/avatars/0.png")
        
        return embed
    
    async def process_payments(self, user_id, username):
        """View payment history"""
        logger.info(f"Viewing payment history for {username} ({user_id})")
        
        # Ensure user exists in database
        self.db.create_user(user_id, username)
        
        # Get all user payments
        payments = self.db.get_user_payments(user_id)
        
        # Log the command
        self.db.log_command(user_id, "payments", "")
        
        # Create response embed
        embed = discord.Embed(
            title="💰 Payment History",
            description=f"View all your payments to Trial Junkie.",
            color=COLORS["info"],
            timestamp=datetime.now()
        )
        
        if not payments:
            embed.add_field(
                name="No Payments Found", 
                value="You haven't made any payments yet. Use `!pay <service>` to get started.", 
                inline=False
            )
        else:
            # Count payments by status
            status_counts = {}
            for payment in payments:
                status = payment['status']
                if status not in status_counts:
                    status_counts[status] = 0
                status_counts[status] += 1
            
            # Add summary field
            embed.add_field(
                name="Summary", 
                value="\n".join([f"**{status.title()}: {count}**" for status, count in status_counts.items()]), 
                inline=False
            )
            
            # Show last 3 payments
            for i, payment in enumerate(payments[:3]):
                created_at = datetime.fromisoformat(payment['created_at'])
                status_emoji = "✅" if payment['status'] == 'completed' else "⏳" if payment['status'] == 'pending' else "❌"
                
                embed.add_field(
                    name=f"{status_emoji} {payment['service_type'].title()} Payment", 
                    value=(
                        f"**Amount:** {payment['amount']} SOL\n"
                        f"**Status:** {payment['status'].title()}\n"
                        f"**Date:** <t:{int(created_at.timestamp())}:R>\n"
                        f"**Reference:** {payment['reference'][:10]}..."
                    ), 
                    inline=False
                )
                
            # If more than 3 payments, indicate that
            if len(payments) > 3:
                embed.add_field(
                    name="More Payments", 
                    value=f"**{len(payments) - 3}** more payments not shown.", 
                    inline=False
                )
                
        embed.set_footer(text=f"Requested by {username} | Trial Junkie", icon_url="https://cdn.discordapp.com/embed/avatars/0.png")
        
        return embed
        
    async def process_user_tier(self, user_id, username):
        """View user tier status"""
        logger.info(f"Viewing tier status for {username} ({user_id})")
        
        # Ensure user exists in database
        self.db.create_user(user_id, username)
        
        # Get user tier information
        tier_info = self.db.get_user_tier(user_id)
        
        # Log the command
        self.db.log_command(user_id, "tier", "")
        
        # Get information about the tier
        tier = tier_info['tier']
        tier_data = None
        
        # Get tier information from config
        from config import SERVICE_TIERS
        if tier in SERVICE_TIERS:
            tier_data = SERVICE_TIERS[tier]
        
        # Create response embed
        embed = discord.Embed(
            title="🏆 Your Trial Junkie Membership",
            description=f"Current membership tier and benefits.",
            color=COLORS["info"],
            timestamp=datetime.now()
        )
        
        # Set color based on tier
        if tier == 'premium':
            embed.color = COLORS['success']
        elif tier == 'paid':
            embed.color = COLORS['warning']
        else:
            embed.color = COLORS['info']
        
        # Add tier field
        tier_name = tier.title()
        embed.add_field(
            name="Current Tier", 
            value=f"**{tier_name}**", 
            inline=True
        )
        
        # Add daily limit field
        if tier_data:
            embed.add_field(
                name="Daily Limit", 
                value=f"**{tier_data['daily_limit']}** commands", 
                inline=True
            )
        
        # Add description field
        if tier_data:
            embed.add_field(
                name="Description", 
                value=tier_data['description'], 
                inline=False
            )
        
        # Add expiry field for premium
        if tier == 'premium' and tier_info['membership_expires']:
            expiry = datetime.fromisoformat(tier_info['membership_expires'])
            embed.add_field(
                name="Premium Expires", 
                value=f"<t:{int(expiry.timestamp())}:R>", 
                inline=False
            )
        
        # Add upgrade field for non-premium
        if tier != 'premium':
            embed.add_field(
                name="Upgrade", 
                value="Use `!pay premium` to upgrade to Premium tier for more features and higher limits!", 
                inline=False
            )
        
        embed.set_footer(text=f"Requested by {username} | Trial Junkie", icon_url="https://cdn.discordapp.com/embed/avatars/0.png")
        
        return embed
